### ISSUE TITLE
Also having overlapping issues

### ISSUE THREAD

**Issue by KnightZander** [Saltssaumure/w9x-discord-theme#27]
![image](https://github.com/user-attachments/assets/670be6fb-ff0c-4d21-af93-a6354f6a1b3d)

**Comment by KnightZander** [comment]
Absolutely love it though man, thanks for making this! If that one issue was fixed that would be truly fantastic.

**Comment by techbot2342** [comment]
Came here to open an issue about this. Hope it gets fixed. I love this theme @Saltssaumure

**Comment by EmilyTheFox** [comment]
@techbot2342 I made a tiny fix for a friend which is absolutely a bandaid fix but its 3am and idc about this theme.

You can add
```css
.titleBar_a934d8 {
    top: 27px !important;
    left: 270px;
    right: 120px;
    border-color: white black #22228B white;
    border-width: 1px;
    border-style: solid;
}

.platform-linux .appMount_ea7e65 {
    &::after {
        inset: 27px 120px 0px 270px;
        border-color: white black #22228B white;
        border-width: 1px;
        border-style: solid;
        z-index: 101;
    }
}
```

to the end of the theme file to just move this bar up a little bit (going from 52px from the top to 27px, and giving it a little matching border)

its not the proper way to fix this but idc to unpack and recompile the scss or however scss works (im a backend developer :p idk the frontend magic) I made this fix in notepad
![image](https://github.com/user-attachments/assets/fd8bb88b-ff72-43bc-b9fe-d43f29ad4f2f)
